In [4]:
import numpy as np

In [3]:
x = np.array([2, 1, 4, 3, 5])
i = np.argsort(x)
print(i)

[1 0 3 2 4]


In [4]:
x[i]

array([1, 2, 3, 4, 5])

In [6]:
a = np.arange(15).reshape(3, 5)
a.shape
a.ndim
a.dtype
a.dtype.name 
a.itemsize # number of bits for each item
a.size # number of items
type(a)

b = np.array([1.2, 2.3, 4.5])
b.dtype.name

c = np.array([(1.2, 2.3, 3.4), (2.0, 3.0, 3.0)])

c = np.array( [ [1,2], [3,4] ], dtype=complex )

a = np.zeros((2,2))
print(a)
b = np.ones((1,2))
print(b)
c = np.full((2,2), 7)
print(c)
d = np.eye(2)
print(d)
e = np.random.random((2,2))
print(e)

x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = x + v
print(y)

[[ 0.  0.]
 [ 0.  0.]]
[[ 1.  1.]]
[[7 7]
 [7 7]]
[[ 1.  0.]
 [ 0.  1.]]
[[ 0.37279621  0.96003893]
 [ 0.12708036  0.88977411]]
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]
